### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/npm-lockdown#31]
Hello!
I have this package.json
```json
{
  "name": "bug",
  "version": "0.0.0",
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "lockdown": "0.0.6"
  },
  "devDependencies": {
    "grunt": "^0.4.5"
  }
}
```

When I run `npm install --save-dev grunt-contrib-imagemin && node_modules/.bin/lockdown-relock` I get this stack trace
```
npm WARN package.json uwezo@0.0.0 No description
npm WARN package.json uwezo@0.0.0 No repository field.
npm WARN package.json uwezo@0.0.0 No README data
npm WARN engine imagemin@3.1.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"v0.10.29","npm":"1.4.14"})
 
> pngquant-bin@2.0.3 postinstall /home/andreip/Dev/uwezo/uwezo-presentation/yo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
 
> gifsicle@2.0.1 postinstall /home/andreip/Dev/uwezo/uwezo-presentation/yo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

 
> optipng-bin@2.0.4 postinstall /home/andreip/Dev/uwezo/uwezo-presentation/yo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
 
> jpegtran-bin@2.0.2 postinstall /home/andreip/Dev/uwezo/uwezo-presentation/yo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
grunt-contrib-imagemin@0.9.2 node_modules/grunt-contrib-imagemin
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── async@0.9.0
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, vinyl@0.4.6, through2@0.6.3, concat-stream@1.4.7, imagemin-svgo@4.0.1, meow@2.1.0, vinyl-fs@0.3.13, imagemin-pngquant@4.0.0, imagemin-gifsicle@4.0.0, imagemin-optipng@4.0.0, imagemin-jpegtran@4.0.0)

module.js:169
  var cacheKey = JSON.stringify({request: request, paths: paths});
                      ^
RangeError: Maximum call stack size exceeded
```
Do you have any clue why this happens? Can you reproduce it?
Thank you!

**Comment by jsebfranck** [comment]
Hi,

Same error for me, using lockdown for the first time :(

**Comment by jdsharp** [comment]
Also received this error, first time using

**Comment by jrgm** [comment]
So there's a dependency cycle that leads to an infinite recursion, 
roughly `meow@2.1.0 -> indent-string@^1.1.0 -> repeating@^1.1.0 -> meow@^2.0.0`. 

I can break the cycle with this diff. Untested but output may be reasonable.
```
--- relock.js-orig	2014-08-21 11:41:46.000000000 -0700
+++ relock.js	2015-01-26 15:32:49.000000000 -0800
@@ -67,6 +67,8 @@
   if (data.name) name = data.name;
   if (data.version) version = data.version;
 
+  if (packages[name] && packages[name][version]) return;
+  
   if (name) {
     shasum = getShasum(cache, name, version);
     if (!(name in packages)) packages[name] = {};
```

**Comment by andreicristianpetcu** [comment]
Thank you @jrgm!!! Your fix seems to work! I patched npm-lock on my machine and node_modules/.bin/lockdown-relock passed with no errors generated new entries in lockdown.json! Will we have this in a future version of npm-lockdown?

**Comment by joelhdzfdz** [comment]
+1

**Comment by vladikoff** [comment]
Should be fixed in v0.0.8, tagged on GitHub.

**Comment by andreicristianpetcu** [comment]
Hmm strange `npm install --save lockdown@0.0.8` throws this error
```bash
npm WARN package.json uwezo@0.0.0 No description
npm WARN package.json uwezo@0.0.0 No repository field.
npm WARN package.json uwezo@0.0.0 No README data
npm ERR! Error: version not found: lockdown@0.0.8
npm ERR!     at /home/myuser/dotfiles/dotfiles_subtree/ndenv/versions/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/home/myuser/dotfiles/dotfiles_subtree/ndenv/versions/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/home/myuser/.ndenv/versions/v0.10.36/bin/node" "/home/myuser/.ndenv/versions/v0.10.36/bin/npm" "install" "--save" "lockdown@0.0.8"
npm ERR! cwd /home/myuser/Dev/uwezo/uwezo-presentation/yo
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/myuser/Dev/myproject/yo/npm-debug.log
npm ERR! not ok code 0
```
I will try later, probably it is a npm cache issue.

**Comment by andreicristianpetcu** [comment]
Or this might not be a npm issue, probably you should change `"version": "0.0.8-dev",` to `"version": "0.0.8",`
https://github.com/mozilla/npm-lockdown/blob/c7ceb9ca37fab4ba2639b89f94b88703d4e4d0d2/package.json#L4

**Comment by vladikoff** [comment]
@andreicristianpetcu it is not on npm yet you need to install it via github for now: `npm i mozilla/npm-lockdown#v0.0.8 --save`

**Comment by andreicristianpetcu** [comment]
Thank you @vladikoff ! I don't know the internals of npm packaging :D
this worked for me
```bash
npm i mozilla/npm-lockdown --save
```
I was unable to specify the version but it got the latest `lockdown@0.0.8-dev`
