### ISSUE TITLE
"npm install" with {"preinstall": "lockdown"} on Windows

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/npm-lockdown#34]
Hello, 
```npm install``` fails on Windows7 with this error:
```sh
npm install
npm WARN package.json my_project@0.0.0 No description
npm WARN package.json my_project@0.0.0 No repository field.
npm WARN package.json my_project@0.0.0 No README data
my_project@0.0.0 preinstall c:\projects\my_project\my_project-presentation\yo
lockdown

NPM Lockdown is here to check your dependencies!  Never fear!
using registry: https://registry.npmjs.org/
npm WARN
my_project@0.0.0 preinstall c:\projects\my_project\my_project-presentation\yo
lockdown

package.json my_project@0.0.0 No description
npm WARN package.json my_project@0.0.0 No repository field.
npm WARN package.json my_project@0.0.0 No README dataevents.js:72
       throw er; // Unhandled 'error' event
             ^
Error: getaddrinfo ENOTFOUND
   at errnoException (dns.js:37:11)
   at Object.onanswer [as oncomplete] (dns.js:124:16)npm ERR! my_project@0.0.0 preinstall: lockdown
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the my_project@0.0.0 preinstall script.
npm ERR! This is most likely a problem with the my_project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls my_project
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\projects\my_project\my_project-presentation\yo
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\projects\my_project\my_project-presentation\yo\npm-debug.log
npm ERR! not ok code 0 
```
On GNU/Linux operating systems it works fine (both on Ubuntu 14.04 and CentOS6). It also works on Windows if I run either ```npm install -g lockdown@0.0.6 && lockdown``` or ```npm install lockdown@0.0.6 && node_modules/lockdown/lockdown.js```. I tried with both cmd.exe and git bash.
Do you have any idea what might cause this? Thank you!

**Comment by andreicristianpetcu** [comment]
I also tried setting this in my package.json
```json
  "scripts": {
    "preinstall": "npm install lockdown@0.0.6 && node node_modules/.bin/lockdown"
  }
```
but I get this error
```
C:\projects\uwezo\uwezo-presentation\yo\node_modules\.bin\lockdown:2
basedir=dirname "$0"
       ^
SyntaxError: Unexpected token ILLEGAL
   at Module._compile (module.js:439:25)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)
   at startup (node.js:119:16)
   at node.js:929:3npm ERR! uwezo@0.0.0 preinstall: npm install lockdown@0.0.6 && node node_modules/.bin/lockdown
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the uwezo@0.0.0 preinstall script.
npm ERR! This is most likely a problem with the uwezo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install lockdown@0.0.6 && node node_modules/.bin/lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls uwezo
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\projects\uwezo\uwezo-presentation\yo
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\projects\uwezo\uwezo-presentation\yo\npm-debug.log
npm ERR! not ok code 0 
```

**Comment by raulmatei** [comment]
Hi,

Try:

```
  "scripts": {
    "preinstall": "npm install lockdown && npm run lockdown",
    "lockdown": "./node_modules/.bin/lockdown",
    "lockdown-relock": "./node_modules/.bin/lockdown-relock",
  },
```

I'm using latest version from NPM.

**Comment by andreicristianpetcu** [comment]
Hi @raulmatei! Thank you for your reply! I don't work on that project anymore. If I ever bump into this problem in the future I will try your solution. I did not think of running it in GitBash. I will close this issue since I am the only person affected.

Thank you again!
