### ISSUE TITLE
Error when running lockdown-relock if some npm modules are installed from git

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/npm-lockdown#39]
Here's the traceback using lockdown 0.0.6

```
node_modules/.bin/lockdown-relock

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/Whatevar/.npm/registry.npmjs.org/payment-icons/.cache.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getShasum (/Users/Whatevar/code/payments-ui/node_modules/lockdown/relock.js:100:15)
    at walk (/Users/Whatevar/code/payments-ui/node_modules/lockdown/relock.js:71:14)
    at /Users/Whatevar/code/payments-ui/node_modules/lockdown/relock.js:42:11
    at Array.forEach (native)
    at /Users/Whatevar/code/payments-ui/node_modules/lockdown/relock.js:41:40
    at /Users/Whatevar/code/payments-ui/node_modules/lockdown/node_modules/read-installed/read-installed.js:137:5
```

Project is mozilla/payments-ui and I was looking to move away from committing the static files that webpack might use to build the bundle.

**Comment by SkeLLLa** [comment]
Got the same bug.

**Comment by bassettsj** [comment]
Got the same bug here.

**Comment by marnen** [comment]
Having the same issue, even though none of my NPM packages are installed from Git.

Lockdown 0.0.6, NPM 2.12.1, Node 0.12.7, Mac OS X 10.10.

**Comment by vladikoff** [comment]
@marnen have you tried v0.0.8 ?

**Comment by marnen** [comment]
@vladikoff No, because I didn't realize that 0.0.6 wasn't current. I'll try 0.0.8.

**Comment by marnen** [comment]
0.0.8 appears to work (though I ran into #42).
