### ISSUE TITLE
Error recovering .cache.json for namespaced modules

### ISSUE THREAD

**Issue by ddalmais** [mozilla/npm-lockdown#44]
For a module @test/test 
node_modules/.bin/lockdown-relock return an error 
````
Error: Cannot find module '/home/zzz/.npm/zzz.zzz.rrr.fr/@test/test/.cache.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getShasum (/var/www/app-zzz/node_modules/@test/essais/node_modules/lockdown/relock.js:100:15)
    at walk (/var/www/app-mytf1/node_modules/@test/essais/node_modules/lockdown/relock.js:71:14)
````

the true directory of .cache.json is '/home/zzz/.npm/zzz.zzz.rrr.fr/_40test_252ftest/.cache.json

**Comment by dlo83** [comment]
+1

**Comment by thomaslein** [comment]
+1

**Comment by SEGEEK** [comment]
I am running into a similar issue.  I have a dependency on angular-material which references angular-animate.  When I run ````node_modules/.bin/lockdown-relock```` I get an error of 

> Error: Cannot find module 'C:\<snip>\AppData\Roaming\npm-cache\registry.npmjs.org\angular-animate\.cache.json'
There is no angular-animate folder in the cache.  If I explicitly install the library it seems ok (I get an error on another module that is a dependency instead)

It would be nice if lockdown could find the child dependencies so you wouldn't have to explicitly install all of the dependencies explicitly.
