### ISSUE TITLE
Error during lockdown-relock for a large set of deps

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/npm-lockdown#46]
Trying to use lockdown for [bedrock](https://github.com/mozilla/bedrock/) but am running into the following:

```bash
$ node_modules/.bin/lockdown-relock
module.js:134
  var cacheKey = JSON.stringify({request: request, paths: paths});
                      ^

RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at Function.Module._findPath (module.js:134:23)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at getShasum (/Users/pmclanahan/Projects/bedrock/node_modules/lockdown/relock.js:100:15)
    at walk (/Users/pmclanahan/Projects/bedrock/node_modules/lockdown/relock.js:71:14)
    at /Users/pmclanahan/Projects/bedrock/node_modules/lockdown/relock.js:80:7
    at Array.forEach (native)
```

Granted, [bedrock's deps list](https://github.com/mozilla/bedrock/blob/634ac47808b27f0ff520025d95549c2eed3dcadd/package.json) is large and some have large deps lists themselves, but it can't be the biggest. I'd really like to only use lockdown for `dependencies` and not `devDependencies`, but I don't see how to only apply the preinstall hook for `npm install --production`.

**Comment by vladikoff** [comment]
Hey @pmclanahan, which version did you try? could you try the latest from Github: https://github.com/mozilla/npm-lockdown/releases 0.0.8

**Comment by pmclanahan** [comment]
Thanks. I was using latest from npm. I'll try this and report back.

**Comment by pmclanahan** [comment]
Worked great. Thanks!

**Comment by vladikoff** [comment]
@seanmonstar we might need to release the latest version on npm
