### ISSUE TITLE
Error with the hook

### ISSUE THREAD

**Issue by nikolay** [mozilla/npm-lockdown#49]
```
> lockdown-relock

module.js:147
  var cacheKey = JSON.stringify({request: request, paths: paths});
                      ^

RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at Function.Module._findPath (module.js:147:23)
    at Function.Module._resolveFilename (module.js:337:25)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at getShasum (/Users/user/Projects/project/node_modules/lockdown/relock.js:100:15)
    at walk (/Users/user/Projects/project/node_modules/lockdown/relock.js:71:14)
    at /Users/user/Projects/project/node_modules/lockdown/relock.js:80:7
    at Array.forEach (native)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/user/Projects/project/.env/pyenv/versions/3.5.1/envs/project/bin/node" "/Users/user/Projects/project/.env/pyenv/versions/project/bin/npm" "run" "lockdown-relock"
```

**Comment by barendb** [comment]
I got this too, 0.0.8-dev solved the issue for me
